fix some problem

diff --git a/.github/workflows/Build-OP-CUDY-TR3000-V1.yml b/.github/workflows/Build-OP-CUDY-TR3000-V1.yml
--- a/.github/workflows/Build-OP-CUDY-TR3000-V1.yml
+++ b/.github/workflows/Build-OP-CUDY-TR3000-V1.yml
@@ -57,6 +57,7 @@ jobs:
       id: codes
       run: |
         git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
+        git clone --depth 1 https://github.com/vernesong/OpenClash.git OpenClash
         cd openwrt
         echo 'src-git Qmodem https://github.com/FUjr/QModem.git;main' >> feeds.conf.default
         echo 'src-git istore https://github.com/linkease/istore;main' >> feeds.conf.default
@@ -75,7 +76,8 @@ jobs:
       working-directory: ./openwrt
       run: |
         ./scripts/feeds update -a
-        sed -i 's/PKG_VERSION:=0.46.033/PKG_VERSION:=0.46.079/' feeds/luci/applications/luci-app-openclash/Makefile
+        rm -rf feeds/luci/applications/luci-app-openclash
+        cp -r ../OpenClash/luci-app-openclash feeds/luci/applications/
         ./scripts/feeds install -a
         
     - name: Configuration Customization
@@ -89,7 +91,7 @@ jobs:
       id : download
       run: |
         cd openwrt/
-        make download -j$(nproc) || { echo "Download failed"; exit 1; }
+        make download -j1 || { echo "Download failed"; exit 1; }
         find dl -size -1024c -delete
         echo "status=success" >> $GITHUB_OUTPUT
 
diff --git a/.github/workflows/Build_OP_JDC_ER1.yml b/.github/workflows/Build_OP_JDC_ER1.yml
--- a/.github/workflows/Build_OP_JDC_ER1.yml
+++ b/.github/workflows/Build_OP_JDC_ER1.yml
@@ -54,6 +54,7 @@ jobs:
     - name: Clone source code
       run: |
         git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
+        git clone --depth 1 https://github.com/vernesong/OpenClash.git OpenClash
         cd openwrt
         # git clone https://github.com/sirpdboy/luci-app-eqosplus package/luci-app-eqosplus
         echo 'src-git Qmodem https://github.com/FUjr/QModem.git;main' >> feeds.conf.default
@@ -72,7 +73,8 @@ jobs:
       working-directory: ./openwrt
       run: |
         ./scripts/feeds update -a
-        sed -i 's/PKG_VERSION:=0.46.033/PKG_VERSION:=0.46.079/' feeds/luci/applications/luci-app-openclash/Makefile
+        rm -rf feeds/luci/applications/luci-app-openclash
+        cp -r ../OpenClash/luci-app-openclash feeds/luci/applications/
         ./scripts/feeds install -a
         ./scripts/feeds install -a -f -p modem
 
@@ -86,7 +88,7 @@ jobs:
     - name: Download package
       run: |
         cd openwrt/
-        make download -j$(nproc) || { echo "::error::下载失败"; exit 1; }
+        make download -j1 || { echo "::error::下载失败"; exit 1; }
         find dl -size -1024c -delete
 
     - name: Compile the OpenWrt
diff --git a/.github/workflows/Build_OP_Netcore_N60PRO.yml b/.github/workflows/Build_OP_Netcore_N60PRO.yml
--- a/.github/workflows/Build_OP_Netcore_N60PRO.yml
+++ b/.github/workflows/Build_OP_Netcore_N60PRO.yml
@@ -57,6 +57,7 @@ jobs:
       if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
       run: |
         git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
+        git clone --depth 1 https://github.com/vernesong/OpenClash.git OpenClash
 
     - name: Setup disk space
       run: |
@@ -70,7 +71,8 @@ jobs:
       working-directory: ./openwrt
       run: |
         ./scripts/feeds update -a
-        sed -i 's/PKG_VERSION:=0.46.033/PKG_VERSION:=0.46.079/' feeds/luci/applications/luci-app-openclash/Makefile
+        rm -rf feeds/luci/applications/luci-app-openclash
+        cp -r ../OpenClash/luci-app-openclash feeds/luci/applications/
         ./scripts/feeds install -a
 
     - name: Configuration Customization
@@ -87,7 +89,7 @@ jobs:
     - name: Download packages
       working-directory: ./openwrt
       run: |
-        make download -j$(nproc) || { echo "❌ Download failed"; exit 1; }
+        make download -j1 || { echo "❌ Download failed"; exit 1; }
         find dl -size -1024c -delete
 
     - name: Compile firmware
diff --git a/.github/workflows/Build_OP_OrangePi_R1_Plus.yml b/.github/workflows/Build_OP_OrangePi_R1_Plus.yml
--- a/.github/workflows/Build_OP_OrangePi_R1_Plus.yml
+++ b/.github/workflows/Build_OP_OrangePi_R1_Plus.yml
@@ -14,6 +14,8 @@ on:
           - false
 
 env:
+  REPO_URL="https://github.com/coolsnowwolf/lede"
+  REPO_BRANCH="master"
   UPLOAD_BIN_DIR: true
   UPLOAD_FIRMWARE: true
   UPLOAD_RELEASE: true
@@ -53,8 +55,6 @@ jobs:
       id: clone
       if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
       run: |
-        REPO_URL="https://github.com/coolsnowwolf/lede"
-        REPO_BRANCH="master"
         git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
         git clone --depth 1 https://github.com/vernesong/OpenClash.git OpenClash
         cd openwrt
@@ -79,21 +79,19 @@ jobs:
       if: steps.clone.outputs.status == 'success'
       run: |
         ./scripts/feeds update -a
-        if [[ "${{ inputs.repo }}" == "lede" ]]; then
-            rm -rf feeds/luci/applications/luci-app-openclash
-            cp -r ../OpenClash/luci-app-openclash feeds/luci/applications/
-        fi
+        rm -rf feeds/luci/applications/luci-app-openclash
+        cp -r ../OpenClash/luci-app-openclash feeds/luci/applications/
         ./scripts/feeds install -a
 
     - name: Configuration Customization
       run: |
         cp config/Xunlong_OrangePi_R1_Plus.config openwrt/.config
-        # cd openwrt && make defconfig
+        cd openwrt && make defconfig
         
     - name: Download packages
       working-directory: ./openwrt
       run: |
-        make download -j$(nproc) || { echo "❌ Download failed"; exit 1; }
+        make download -j1 || { echo "❌ Download failed"; exit 1; }
         find dl -size -1024c -delete
 
     - name: Compile firmware
